-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 11:12:58 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Товары`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Товары` (
  `id_Товары` INT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `артикул` VARCHAR(50) NULL,
  `категория` VARCHAR(50) NULL,
  `ед_изм` VARCHAR(10) NULL,
  PRIMARY KEY (`id_Товары`),
  UNIQUE INDEX `артикул_UNIQUE` (`артикул` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Складские_ячейки`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Складские_ячейки` (
  `id_ячейки` INT NULL AUTO_INCREMENT,
  `номер` VARCHAR(10) NOT NULL,
  `зона` VARCHAR(50) NULL,
  `id_товара` INT NULL,
  PRIMARY KEY (`id_ячейки`, `id_товара`),
  UNIQUE INDEX `номер_UNIQUE` (`номер` ASC) VISIBLE,
  INDEX `id_товара_idx` (`id_товара` ASC) VISIBLE,
  CONSTRAINT `Товары`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`Товары` (`id_Товары`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Отгрузки`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Отгрузки` (
  `id_Отгрузки` INT NULL AUTO_INCREMENT,
  `дата` DATE NOT NULL,
  `количество` DECIMAL(12,3) NOT NULL,
  `покупатель` VARCHAR(100) NOT NULL,
  `id_товара` INT NULL,
  PRIMARY KEY (`id_Отгрузки`, `id_товара`),
  INDEX `Товары_idx` (`id_товара` ASC) VISIBLE,
  CONSTRAINT `Товары`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`Товары` (`id_Товары`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Поставщики`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Поставщики` (
  `id_Поставщика` INT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `инн` VARCHAR(12) NULL,
  `телефон` VARCHAR(20) NULL,
  `адрес` VARCHAR(200) NULL,
  `контактное_лицо` VARCHAR(100) NULL,
  PRIMARY KEY (`id_Поставщика`),
  UNIQUE INDEX `инн_UNIQUE` (`инн` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Поступления`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Поступления` (
  `id_Поступления` INT NULL AUTO_INCREMENT,
  `дата` DATE NOT NULL,
  `количество` DECIMAL(12,3) NOT NULL,
  `цена_закупки` DECIMAL(10,2) NULL,
  `id_поставщика` INT NULL,
  `id_товара` INT NULL,
  PRIMARY KEY (`id_Поступления`, `id_поставщика`, `id_товара`),
  INDEX `Поставщики_idx` (`id_поставщика` ASC) VISIBLE,
  INDEX `Товары_idx` (`id_товара` ASC) VISIBLE,
  CONSTRAINT `Поставщики`
    FOREIGN KEY (`id_поставщика`)
    REFERENCES `mydb`.`Поставщики` (`id_Поставщика`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Товары`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`Товары` (`id_Товары`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
